### model
model_name_or_path: Qwen/Qwen3-8B
trust_remote_code: true
enable_thinking: false

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: chess_forum_conversation,gpt4_chess_conversation,chess_modeling_gpt4
template: qwen3
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen3-8b/full/first_stage_knowledge_injection
logging_steps: 10
save_steps: 300
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
mask_history: true
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 5.0e-6
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null


### eval
do_eval: true
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 300
